spring:
  thymeleaf:
      cache: false
      mode: HTML5
      encoding: UTF-8
      servlet:
        content-type: text/html
      prefix: classpath:/templates/
      suffix: .html
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/hospital?autoReconnect=true&useUnicode=true&characterEncoding=utf8
      username: root
      password: lovewlgzs
      driver-class-name: com.mysql.jdbc.Driver
mybatis:
    type-aliases-package: org.wlgzs.hospitalmanage.entity
logging:
  config: classpath:logback-spring.xml
server:
  port: 8182
