spring:
  thymeleaf:
      cache: false
      mode: HTML5
      encoding: UTF-8
      servlet:
        content-type: text/html
      prefix: classpath:/templates/
      suffix: .html
  datasource:
    druid:
      url: jdbc:mysql://localhost:3307/hospital?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
mybatis:
    type-aliases-package: org.wlgzs.hospitalmanage.entity
logging:
  config: classpath:logback-spring.xml
server:
  port: 8080
